### ISSUE TITLE
Not marking the catchup channels 

### ISSUE THREAD

**Issue by yannydodo12** [stingray82/e2m3u2bouquet-tools#1]
Hi mate the mod doesn't seem to mark the catchup channels for me.

**Comment by stingray82** [comment]
@yannydodo12 ,

I am going to need some more information I just ran it on the command line without fail;

![image](https://user-images.githubusercontent.com/11146912/52011783-d3fecf00-24d0-11e9-9690-2f88c42449f0.png)

And it generated the bouquets correctly with the applicable bang in this case !!!

![screenshot_20190130204851](https://user-images.githubusercontent.com/11146912/52011692-9ac65f00-24d0-11e9-9723-cc7c1d22e5b8.jpg)

I then tested it using the plugin which also worked as expected.

![screenshot_20190130210344](https://user-images.githubusercontent.com/11146912/52012480-8d11d900-24d2-11e9-9f00-10547579b866.jpg)

The only thing I have been unable to test is the published install method as I am using openATV 6.3 and there is a WGET issue with openATV & GitHub regarding the SSL certificate, but I manually downloaded it deleted it and renamed it from GitHub and then restarted the GUI

Thanks
~ Stingray

**Comment by yannydodo12** [comment]
I'm not doubting it's working mate just doesn't seem to mark my provider catchup channels. I'm using the plugin 0.8.2. And openatv 6.3 
I know the old mod used to work fine so I'm not sure why it's not working now.
And yeah I just used the --no-check-certificate to install on openatv and tried the manual install way aswell

**Comment by stingray82** [comment]
@yannydodo12 

I am using an xtreme provider is yours a vaders reseller? That's the only difference I can possibly see if you run it from the command line do you get an error message?

Use terminal / putty and assuming you're using the plugin run as below if you haven't set up a config file:
First:
 `chmod 755 /usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet/e2m3u2bouquet.py `
Second:
`/usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet/e2m3u2bouquet.py -m="Insert your providers Playlist URL here" -e="Providers EPG URL Here" -n"Providers Name"`
Third:
`wget -O /dev/null -q http://127.0.0.1/web/powerstate?newstate=3`

If using a config file:
First: 
`Chmod /usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet/e2m3u2bouquet.py 755 `
Second:
`/usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet/e2m3u2bouquet.py`
Third:
`wget -O /dev/null -q http://127.0.0.1/web/powerstate?newstate=3`

Then post if you get any errors up so I can take a look please see what is going wrong

~ Stingray

**Comment by yannydodo12** [comment]
Will try that in a few minutes mate and not using vaders 
I've just tried the script and it marks them.
Sorry don't know how to add a picture lol.
Will try what you said there now

**Comment by yannydodo12** [comment]
Ooopsie, Something happened while trying to bang catchup names: No JSON object could be found. That's the error I'm getting

**Comment by yannydodo12** [comment]
![20190130_222631](https://user-images.githubusercontent.com/47193747/52017072-35796a80-24de-11e9-807e-063e7c2cb8ac.jpg)

**Comment by stingray82** [comment]
@yannydodo12 What do you get if you go here:

http://Yourhosthere.com:port/player_api.php?username=YourUserNameHere&password=YourPasswordHere&action=get_live_streams&start=99990000000000 

The script is looking for the channels identified as catchup "tv_archive_duration":"1"  this is telling it the channels it needs to modify with a Bang if a set of data pulls up can you see and find the tv_archive_duration":"1?

**Comment by yannydodo12** [comment]
CBEEBIES HD","added":"1508859172","category_id":"5","custom_sid":":0:1:18ae:7fd:2:11a0000:0:0:0:","tv_archive":1,"direct_source":"","tv_archive_duration":"7"},{"num":228,

**Comment by stingray82** [comment]
I am going to need to know the provider details to see where this is going wrong whats the domain name for the provider i.e the http://provider.com I'll see if I can grab a trial or a 1-day pass if it used to work in older versions, it should work now.

**Comment by yannydodo12** [comment]
It works fine if I run the script 
![20190130_215014](https://user-images.githubusercontent.com/47193747/52018035-09131d80-24e1-11e9-8342-f5c1c2117b2a.jpg)

**Comment by stingray82** [comment]
was that as a config file or as a line call 
So A:
/usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet/e2m3u2bouquet.py
Or B:
/usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet/e2m3u2bouquet.py -m="Insert your providers Playlist URL here" -e="Providers EPG URL Here" -n"Providers Name"

**Comment by yannydodo12** [comment]
./e2m3u2bouquet.py -m "http://provider_url/get.php?username=YOURUSERNAME&password=YOURPASSWORD&type=m3u_plus&output=ts" -e "http://provider_url

**Comment by yannydodo12** [comment]
I put your file in /etc/enigma2/e2m3u2bouquet 
Chomod it to 755
Then 
cd etc/enigma2/e2m3u2bouquet 
Then 
./e2m3u2bouquet.py -m "http://provider_url/get.php?username=YOURUSERNAME&password=YOURPASSWORD&type=m3u_plus&output=ts" -e "http://provider_url/xmltv.php?username=YOURUSERNAME&password=YOURPASSWORD"

**Comment by yannydodo12** [comment]
![20190130_230121](https://user-images.githubusercontent.com/47193747/52018672-17facf80-24e3-11e9-9917-70ab1eb2de65.jpg)

**Comment by stingray82** [comment]
I am guessing it is something in the config that is breaking if it works with your user details on the command line, have you checked your config file?
Attached is mine i used to test the plugin,

[Config.txt](https://github.com/stingray82/e2m3u2bouquet-tools/files/2814884/Config.txt)

it's located in /etc/enigma2/e2m3u2bouquet

you can open it edit it and paste it over the top of your existing one

**Comment by yannydodo12** [comment]
Yeah it's fine but I just tried your one but it's still the same no marking 
How can I send you the providers hosting as don't want to post on open forum lol.

**Comment by stingray82** [comment]
I am not really sure if you can do that on GitHub I have telegram for such
issues and have setup a group if you join that

I will revoke the link once you've joined and it will be a private chat
then.

~Stingray

**Comment by yannydodo12** [comment]
Joined there now mate

**Comment by stingray82** [comment]
I have revoked the link, have removed it and now sent you a message on Telegram, no rush as Its likely to be tomorrow now before I can look

**Comment by stingray82** [comment]
Closed as no contact for three days and can't replicate issue

**Comment by yannydodo12** [comment]
So did ya get it to work on the provider I sent you?

**Comment by yannydodo12** [comment]
Hi mate won't let me message you turn on comments in group

**Comment by yannydodo12** [comment]
![screenshot_2019-02-02-15-31-51](https://user-images.githubusercontent.com/47193747/52165997-b95e6d00-26ff-11e9-82ba-52cd8f16d033.png)

**Comment by stingray82** [comment]
@yannydodo12 

I have sent you a message on telegram with my working config file and screenshots, I couldn't replicate this issue, to help any more I am going to need a screenshot inside the following directory 
/usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet

Like the below to look for install errors:
![image](https://user-images.githubusercontent.com/11146912/52166420-df3a4080-2704-11e9-98ed-04deef52fd73.png)


~Stingray
